name: Authenticate

on:
  workflow_call:
    secrets:
      GCP_WORKLOAD_IDENTITY_POOL:
        required: true
      GCP_SERVICE_ACCOUNT_EMAIL:
        required: true

jobs:
  auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (needed for workspace setup)
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_POOL }}/providers/github
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          export_environment_variables: true
          create_credentials_file: true
